create table nodes (pub_key varchar(64) primary key, raw_data varchar(2048));
create table channels (funding_tx varchar(64), output_idx integer, node_1 varchar(64), node_2 varchar(64), raw_data varchar(2048), constraint pk_funding_tx_output_idx primary key (funding_tx, output_idx), constraint fk_node_1 foreign key (node_1) references nodes (pub_key), constraint fk_node_2 foreign key (node_2) references nodes (pub_key));
create table node_snapshots (node varchar(64), timestamp integer, constraint fk_node foreign key (node) references nodes (pub_key), constraint pk_node_timestamp primary key (node, timestamp));
create table channel_snapshots (channel varchar(64), idx integer, timestamp integer, constraint fk_channel_idx foreign key (channel, idx) references channels (funding_tx, output_idx), constraint pk_channel_idx_timestamp primary key (channel, idx, timestamp));
create table potential_txes (tx varchar(64), raw_data varchar(2048), constraint pk_tx primary key (tx), constraint fk_tx foreign key (tx) references channels (funding_tx));
create table potential_txes_less_restrictive (tx varchar(64), raw_data varchar(2048), constraint pk_tx primary key (tx), constraint fk_tx foreign key (tx) references channels (funding_tx));

create table nodes (pub_key varchar(64) primary key, raw_data json_text);
create table channels (funding_tx varchar(64), output_idx integer, node_1 varchar(64), node_2 varchar(64), raw_data json_text, constraint pk_funding_tx_output_idx primary key (funding_tx, output_idx), constraint fk_node_1 foreign key (node_1) references nodes (pub_key), constraint fk_node_2 foreign key (node_2) references nodes (pub_key));
create table node_snapshots (node varchar(64), timestamp integer, constraint fk_node foreign key (node) references nodes (pub_key), constraint pk_node_timestamp primary key (node, timestamp));
create table channel_snapshots (channel varchar(64), idx integer, timestamp integer, constraint fk_channel_idx foreign key (channel, idx) references channels (funding_tx, output_idx), constraint pk_channel_idx_timestamp primary key (channel, idx, timestamp));
create table potential_txes (tx varchar(64), raw_data json_text, constraint pk_tx primary key (tx), constraint fk_tx foreign key (tx) references channels (funding_tx));
create table potential_txes_less_restrictive (tx varchar(64), raw_data json_text, constraint pk_tx primary key (tx), constraint fk_tx foreign key (tx) references channels (funding_tx));